- name: vagrant-maas
  hosts: vagrant
  user: vagrant
  gather_facts: False
  sudo: True
  tasks:
    - name: Install base packages and other usefulness
      action: apt pkg={{ item }} state=installed update_cache=yes
      with_items:
        - language-pack-en-base
    - name: Install cloud packages
      shell: dpkg -i /vagrant/cloud-install-common*deb /vagrant/cloud-install-multi*deb
    - name: Install dependencies
      shell: apt-get install -f -yy
