- hosts: all
  user: vagrant
  gather_facts: False
  sudo: True
  tasks:
    - name: Install base packages and other usefulness
      action: apt pkg={{ item }} state=installed update_cache=yes
      with_items:
        - language-pack-en-base